baseURL = "https://hko0451.github.io/"
languageCode = "en-us"
title = "hko0451's blog"
theme = "mainroad"

[Author]
  name = "Hyeonjong Ko"

[Params]
  description = "Hyeonjong's personal blog about programming"
  copyright = "Hyeonjong Ko"
  opengraph = true
  schema = true
  readmore = true
  authorbox = true
  toc = true
  pager = true
  post_meta = ["author", "date", "categories", "translations"]
  mainSections = ["post", "blog", "news"]

[Params.thumbnail]
  visibility = ["list", "post"]

[Params.sidbar]
  home = "right"
  list = "left"
  single = false
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5
  categories_counter = false
  tags_counter = false

[Params.widgets.social]
  github = "hko0451"
  email = "hyeonjong9999@gmail.com"

[Params.widgets.search]
  url = "https://google.com/search"
  [Params.widgets.search.input]
    name = "sitesearch"
    pre = ""
